# Generated by Django 3.0.2 on 2020-01-14 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time', models.DateTimeField()),
                ('edittime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayname', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('displayname', models.CharField(max_length=256)),
                ('remark', models.TextField()),
                ('resolve_alias', models.CharField(max_length=256)),
                ('public', models.BooleanField()),
                ('finished_cuts', models.BooleanField()),
                ('finished_wiki_transfer', models.BooleanField()),
                ('needs_payment', models.BooleanField()),
                ('import_claim_time', models.DateTimeField()),
                ('is_printonly', models.BooleanField()),
                ('has_solution', models.BooleanField()),
                ('solution_printonly', models.BooleanField()),
                ('master_solution', models.CharField(max_length=512)),
                ('legacy_solution', models.CharField(max_length=512)),
                ('is_oral_transcript', models.BooleanField()),
                ('oral_transcript_checked', models.BooleanField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Category')),
                ('exam_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='answers.ExamType')),
                ('import_claim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_claim_set', to=settings.AUTH_USER_MODEL)),
                ('oral_transcript_uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oral_transcript_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time', models.DateTimeField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.Answer')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_num', models.IntegerField()),
                ('rel_height', models.FloatField()),
                ('cut_version', models.IntegerField(default=1)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.Exam')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.AnswerSection'),
        ),
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='downvotes',
            field=models.ManyToManyField(related_name='downvoted_answer_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='expertvotes',
            field=models.ManyToManyField(related_name='expertvote_answer_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='upvotes',
            field=models.ManyToManyField(related_name='upvoted_answer_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
