# Generated by Django 3.0.2 on 2020-01-15 12:51

import answers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_auto_20200114_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='long_id',
            field=models.CharField(default=answers.models.generate_long_id, max_length=256),
        ),
        migrations.AddField(
            model_name='comment',
            name='long_id',
            field=models.CharField(default=answers.models.generate_long_id, max_length=256),
        ),
    ]
