# Generated by Django 3.0.2 on 2020-01-15 20:18

import answers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0004_auto_20200115_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='long_id',
            field=models.CharField(default=answers.models.generate_long_id, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='long_id',
            field=models.CharField(default=answers.models.generate_long_id, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='filename',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
