# Generated by Django 3.0.2 on 2020-01-15 20:18

from django.db import migrations


def add_default_exam_types(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Type = apps.get_model('answers', 'ExamType')
    Type.objects.using(db_alias).create(displayname='Exams')
    Type.objects.using(db_alias).create(displayname='Transcripts')
    Type.objects.using(db_alias).create(displayname='Midterms')
    Type.objects.using(db_alias).create(displayname='Endterms')
    Type.objects.using(db_alias).create(displayname='Finals')


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0005_auto_20200115_2018'),
    ]

    operations = [
        migrations.RunPython(add_default_exam_types)
    ]
