# Generated by Django 3.0.2 on 2020-01-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0006_auto_20200115_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='import_claim_time',
            field=models.DateTimeField(null=True),
        ),
    ]
