# Generated by Django 3.0.2 on 2020-01-16 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0007_auto_20200115_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='answers.ExamType'),
            preserve_default=False,
        ),
    ]
