# Generated by Django 3.0.2 on 2020-01-16 15:57

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('answers', '0008_auto_20200116_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='flagged',
            field=models.ManyToManyField(related_name='flagged_answer_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='is_legacy_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='edittime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
