# Generated by Django 4.1.13 on 2023-12-26 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("answers", "0015_alter_comment_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="is_legacy_answer",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="finished_wiki_transfer",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="is_oral_transcript",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="is_printonly",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="legacy_solution",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="needs_payment",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="oral_transcript_checked",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="oral_transcript_uploader",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="solution_printonly",
        ),
    ]
