# Generated by Django 4.1.13 on 2025-05-26 02:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('answers', '0016_remove_exam_finished_wiki_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='flagged',
            field=models.ManyToManyField(related_name='flagged_%(app_label)s_comments_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
