# Generated by Django 4.1.13 on 2025-06-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0016_remove_answer_is_legacy_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]