# Generated by Django 4.1.13 on 2024-03-05 18:04

from django.db import migrations, models

def migrate_to_answer_kinds(apps, schema_editor):
    Answer = apps.get_model("answers", "Answer")
    Answer.objects.filter(is_legacy_answer=False).update(kind='legacy')


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0016_remove_exam_finished_wiki_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='kind',
            field=models.CharField(choices=[('personal', 'Personal'), ('legacy', 'Legacy'), ('official', 'Official')], default='personal', max_length=16),
        ),
        migrations.RunPython(migrate_to_answer_kinds),
        migrations.RemoveField(
            model_name='answer',
            name='is_legacy_answer',
        ),
    ]
