# Generated by Django 4.1.13 on 2026-03-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0018_migrate_legacy_to_answer_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="dark_mode_warning",
            field=models.BooleanField(default=False),
        ),
    ]
