# Generated by Django 4.1.13 on 2026-02-24 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0019_20260312_merge_upstream_migrate_legacy_to_answer_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examword',
            name='flow',
        ),
        migrations.DeleteModel(
            name='ExamPageFlow',
        ),
        migrations.DeleteModel(
            name='ExamWord',
        ),
    ]
