# Generated by Django 4.1.13 on 2026-03-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0019_remove_examword_flow_delete_exampageflow_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="dark_mode_warning",
            field=models.BooleanField(default=False),
        ),
    ]