# Generated by Django 4.1.13 on 2026-03-17 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("answers", "0021_20260312_merge_upstream_exam_dark_mode_warning"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="marked_as_ai",
            field=models.ManyToManyField(
                related_name="markedasai_answer_set", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="marked_as_ai",
            field=models.ManyToManyField(
                related_name="markedasai_%(app_label)s_comments_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
