# Generated by Django 4.1.13 on 2026-04-25 12:13

import django.db.models.deletion
import django_prometheus.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "answers",
            "0022_20260428_merge_upstream_mark_as_ai",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamUserSolved",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="answers.exam"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solved_exams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("exam_user_solved"),
                models.Model,
            ),
        ),
        migrations.AddConstraint(
            model_name="examusersolved",
            constraint=models.UniqueConstraint(
                fields=("exam", "user"), name="unique_user_exam_solve"
            ),
        ),
    ]
