# Generated by Django 4.1.13 on 2025-06-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dissertation',
            name='study_level',
            field=models.CharField(choices=[('UG4', 'UG4'), ('UG5', 'UG5'), ('MSc', 'MSc')], default='UG4', max_length=3),
        ),
    ]
