# Generated by Django 4.1.13 on 2025-06-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertations', '0002_dissertation_study_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='dissertation',
            name='grade_band',
            field=models.CharField(blank=True, choices=[('40-49', '40-49'), ('50-59', '50-59'), ('60-69', '60-69'), ('70-79', '70-79'), ('80-89', '80-89'), ('90-100', '90-100')], max_length=6, null=True),
        ),
    ]
