# Generated by Django 4.1.13 on 2026-04-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0019_coursestats_course_organiser"),
        ("dissertations", "0004_dissertation_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="dissertation",
            name="relevant_categories",
            field=models.ManyToManyField(
                related_name="relevant_dissertations", to="categories.category"
            ),
        ),
    ]
