# Generated by Django 4.1.13 on 2026-07-19 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0019_coursestats_course_organiser"),
        ("ediauth", "0007_temporaryuser"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("slug", models.CharField(max_length=256, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("guide", "Guide"), ("static_html", "Static Html")],
                        default="guide",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("edited_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("content", models.TextField(default="")),
                ("anonymised", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PageAuthor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("file", "File")], default="file", max_length=16
                    ),
                ),
                ("display_name", models.CharField(max_length=256)),
                ("filename", models.CharField(max_length=256, unique=True)),
                ("mime_type", models.CharField(max_length=256)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to="pages.page",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PageRevision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "title_delta",
                    models.TextField(default="")
                ),
                ("content_delta", models.TextField(default="")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_revisions",
                        to="pages.pageauthor",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="pages.page",
                    ),
                ),
                (
                    "message",
                    models.TextField(default=""),
                ),
                (
                    "anonymised",
                    models.BooleanField(default=False),
                ),
                (
                    "redacted",
                    models.BooleanField(default=False),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pageauthor",
            name="temp_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ediauth.temporaryuser",
            ),
        ),
        migrations.AddField(
            model_name="pageauthor",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authored_pages",
                to="pages.pageauthor",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="category",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="page",
                to="categories.category",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="parents",
            field=models.ManyToManyField(related_name="children", to="pages.page"),
        ),
    ]
