# Generated by Django 4.1.13 on 2026-07-19 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ediauth", "0007_temporaryuser"),
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageauthor",
            name="temp_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ediauth.temporaryuser",
            ),
        ),
        migrations.DeleteModel(
            name="TemporaryUser",
        ),
    ]
