# Generated by Django 4.1.13 on 2026-07-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_pageauthor_temp_user_delete_temporaryuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagerevision",
            name="message",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="pagerevision",
            name="title_delta",
            field=models.TextField(default=""),
        ),
    ]
