# Generated by Django 4.1.13 on 2026-07-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_pagerevision_message_pagerevision_title_delta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pageauthor",
            name="is_anonymous",
        ),
        migrations.AddField(
            model_name="pagerevision",
            name="anonymised",
            field=models.BooleanField(default=False),
        ),
    ]
