# Generated by Django 4.1.13 on 2026-07-20 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0019_coursestats_course_organiser"),
        ("pages", "0004_remove_pageauthor_is_anonymous_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="category",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="page",
                to="categories.category",
            ),
        ),
    ]
