# Generated by Django 5.2.16 on 2026-08-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_page_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagerevision',
            name='redacted',
            field=models.BooleanField(default=False),
        ),
    ]
