# Generated by Django 5.2.16 on 2026-08-10 23:19

import datetime

import django.db.models.deletion
from django.db import migrations, models
import requests

from pages.api import calculate_patch, create_page_nochecks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_pageparent_alter_page_parents'),
    ]

    def create_pages_for_categories(apps, schema_editor):
        Page = apps.get_model('pages', 'Page')
        PageAuthor = apps.get_model('pages', 'PageAuthor')
        PageRevision = apps.get_model('pages', 'PageRevision')
        Category = apps.get_model('categories', 'Category')
        TemporaryUser = apps.get_model('ediauth', 'TemporaryUser')

        # Create temporary user
        temp_user = TemporaryUser.objects.create()
        temp_author = PageAuthor.objects.create(temp_user=temp_user)

        for category in Category.objects.all():
            if category.page is not None:
                continue

            page = create_page_nochecks(
                title=category.displayname,
                kind=Page.Kind.GUIDE,
                category=category,
                author=temp_author,
                parents=[],
                is_anonymous=True
            )

            if category.more_markdown_link:
                r = requests.get(category.more_markdown_link)
                new_content = r.text if r.status_code == 200 else ""
                content_patch = calculate_patch(page.content, new_content)
                page.content = content_patch
                page.edited_at = datetime.datetime.now(datetime.UTC)
                page.save()

                # Create new revision
                PageRevision.objects.create(
                    page=page,
                    author=temp_author,
                    anonymised=False,
                    content_delta=content_patch,
                    title_delta="",
                    message="Imported from pre-existing file at " + category.more_markdown_link,
                )

    def reverse_create_pages_for_categories(apps, schema_editor):
        Category = apps.get_model('categories', 'Category')

        for category in Category.objects.all():
            if category.page is not None:
                category.page.delete()

    operations = [
        migrations.RunPython(
            create_pages_for_categories,
            reverse_code=reverse_create_pages_for_categories,
        )
    ]
