# Generated by Django 4.1.13 on 2026-04-24 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0002_20260428_merge_upstream_feedback_reply"),
        ("notifications", "0003_notificationsetting_email_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="feedback",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="feedback.feedback",
            ),
        ),
    ]
