# Generated by Django 4.1.13 on 2024-04-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsetting",
            name="email_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
