# Generated by Django 4.1.13 on 2026-04-24 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_feedback_reply_feedback_reply_time"),
        ("notifications", "0002_notification_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="feedback",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="feedback.feedback",
            ),
        ),
    ]
