version: "3.4"

services:
  react-frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    extra_hosts:
      - "minio:127.0.0.1"
    environment:
      - BACKEND_HOST=community-solutions:80

# connects to the same network as the backend
networks:
  default:
    name: community-solutions
