variables:
  KUBERNETES_CPU_LIMIT: "8"
  KUBERNETES_CPU_REQUEST: "1500m"
  KUBERNETES_MEMORY_REQUEST: "1600Mi"
  KUBERNETES_MEMORY_LIMIT: "3Gi"

  UV_LINK_MODE: copy
  UV_SYSTEM_PYTHON: 1
  UV_CACHE_DIR: .uv-cache

# List of stages for jobs, which is executed in order. To define dependencies
# between jobs in the same stage, use the 'needs' keyword.
stages:
  - Build
  - Lint and Test

"Generate OpenAPI":
  stage: Build
  tags: [kata]
  image: python:3.9-bookworm
  before_script:
    - pip install uv
    - cd backend
  script:
    - uv run manage.py export_openapi
  after_script:
    - cd backend
    - uv cache prune --ci
  cache:
    key:
      files:
        - backend/uv.lock
    paths:
      - backend/.uv-cache
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
  artifacts:
    paths:
      - ./backend/static/openapi.json

"Backend Check":
  stage: Lint and Test
  tags: [kata]
  needs:
    - artifacts: true
      job: "Generate OpenAPI"
  rules:
    # This job runs on protected branches and on merge requests to master.
    # Both should be done because the branch state within the MR and the
    # merged result can and often is different if there are other commits
    # merged between the executions.
    - if: $CI_COMMIT_BRANCH == "master" # Run on master, or
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" # Run on merge requests to master
      changes:
        - backend/**/*
  variables:
    MINIO_ACCESS_KEY: minio
    MINIO_SECRET_KEY: minio123
    POSTGRES_DB: testdb
    POSTGRES_USER: testuser
    POSTGRES_PASSWORD: testpw
  services:
    - name: postgres:16
      alias: postgres
      command: ["postgres"]
      variables:
        POSTGRES_HOST_AUTH_METHOD: trust
    - name: minio/minio:RELEASE.2023-10-25T06-33-25Z
      alias: minio
      command: ["server", "/minio"]
  image: python:3.9-bookworm
  before_script:
    - set -euo pipefail

    - apt-get update
    - apt-get install -y curl

    # Install mc so that we can create the community-solutions bucket in minio
    - curl -L https://dl.min.io/client/mc/release/linux-amd64/mc --create-dirs -o mc
    - chmod +x ./mc
    - ./mc alias set myminio http://minio:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
    - ./mc mb myminio/community-solutions

    # Install poppler to get pdftotext binary
    - apt-get install -y poppler-utils
    - pip install uv
    - cd backend
    - uv sync

    # Make/copy files (same as Dockerfile definition) to make resources available to tests
    - mkdir intermediate_pdf_storage
    - mv ../frontend/public/exam10.pdf ./
    - mv ../frontend/public/static/* ./static/
  cache:
    key:
      files:
        - backend/uv.lock
    paths:
      - backend/.uv-cache
  script:
    - export SIP_POSTGRES_DB_NAME=$POSTGRES_DB
    - export SIP_POSTGRES_DB_USER=$POSTGRES_USER
    - export SIP_POSTGRES_DB_PW=$POSTGRES_PASSWORD
    - export SIP_POSTGRES_DB_SERVER=localhost
    - export SIP_POSTGRES_DB_PORT=5432
    - export SIP_S3_FILES_HOST=localhost
    - export SIP_S3_FILES_PORT=9000
    - export SIP_S3_FILES_ACCESS_KEY=$MINIO_ACCESS_KEY
    - export SIP_S3_FILES_SECRET_KEY=$MINIO_SECRET_KEY
    - export SIP_S3_FILES_BUCKET=community-solutions
    - export SIP_S3_FILES_USE_SSL=false
    - uv run manage.py test --parallel # parallel speeds up by approx 4x.
  after_script:
    - cd backend
    - uv cache prune --ci

"Frontend Check":
  stage: Lint and Test
  tags: [kata]
  rules:
    # This job runs on protected branches and on merge requests to master.
    # Both should be done because the branch state within the MR and the
    # merged result can and often is different if there are other commits
    # merged between the executions.
    - if: $CI_COMMIT_BRANCH == "master" # Run on master, or
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" # Run on merge requests to master
      changes:
        - frontend/**/*
  image: node:24
  before_script:
    - set -euo pipefail
    - corepack enable

    # Prepare Yarn to save its store at a known location so it's cachable
    - cp ./backend/static/openapi.json ./frontend/public/openapi.json
    - cd frontend
    - yarn config set enableGlobalCache false

    # Fetch the merge target branch so we can compare and find the diff (only
    # for merge requests)
    - |
      if [[ -n ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME-} ]]; then
        git fetch origin "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
      fi
  cache:
    key:
      files:
        - frontend/yarn.lock
    paths:
      - frontend/.yarn/cache/
      - /root/.nvm
  script:
    - yarn
    - yarn codegen
    - echo 'Typechecking...'
    - yarn run tsc
    - echo 'Checking linter errors...'
    - yarn run lint

    # Check formatting errors only for merge requests
    - |
      if [[ -n ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME-} ]]; then
        echo 'Checking formatting errors on modified files...'
        yarn run prettier --check $( \
          git diff --diff-filter=d --name-only --relative origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME $CI_COMMIT_SHA -- \
            "src/**/*.js" \
            "src/**/*.jsx" \
            "src/**/*.ts" \
            "src/**/*.tsx" \
            "src/**/*.json" \
            "src/**/*.css" \
        )
      fi
  needs:
    - artifacts: true
      job: "Generate OpenAPI"
