tasks:
  - name: Environment Setup (Dependency Installation, Backend Compile)
    init: |
      curl -L https://git.io/n-install | bash
      npm install --global yarn
    command: gp sync-done setup

  - name: Start Backend
    init: | 
      gp sync-await setup
      docker-compose build
    command: docker-compose up

  - name: Start frontend
    init: >
      cd frontend && yarn
    command: yarn start

ports:
  - port: 3000
    onOpen: open-preview
  - port: 3001-8999
    onOpen: ignore
