version: "3.4"

services:
  minio:
    image: minio/minio:RELEASE.2023-10-25T06-33-25Z
    container_name: minio
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/export
    command: server /export --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-I", "localhost:9000/minio/health/live"]
      interval: 1s
      timeout: 1s
      retries: 20
  createbuckets:
    image: minio/mc:RELEASE.2023-10-24T21-42-22Z
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c " /usr/bin/mc config host add myminio http://minio:9000 minio minio123; /usr/bin/mc mb myminio/community-solutions; "
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
    volumes:
      - ./data/sql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  community-solutions:
    build:
      context: .
      args:
        git_branch: <docker>
        git_commit: <compose>
      target: backend
    container_name: community-solutions
    ports:
      - "8081:80"
    environment:
      # The following environment variables are used by the backend for local
      # development.

      - DEPLOYMENT_DOMAINS=localhost

      - SIP_POSTGRES_DB_SERVER=postgres
      - SIP_POSTGRES_DB_PORT=5432
      - SIP_POSTGRES_DB_NAME=postgres
      - SIP_POSTGRES_DB_USER=docker
      - SIP_POSTGRES_DB_PW=docker

      - SIP_S3_FILES_HOST=minio
      - SIP_S3_FILES_PORT=9000
      - SIP_S3_FILES_ACCESS_KEY=minio
      - SIP_S3_FILES_SECRET_KEY=minio123
      - SIP_S3_FILES_BUCKET=community-solutions
      - SIP_S3_FILES_USE_SSL=false

      - GSUITE_CREDENTIALS_FILE=credentials.json

      - RUNTIME_COMMUNITY_SOLUTIONS_SESSION_SECRET=42
      - RUNTIME_COMMUNITY_SOLUTIONS_API_KEY=42

      - RUNTIME_JWT_PRIVATE_KEY_PATH=/app/community_solutions_jwt_private.pem
      - RUNTIME_JWT_PUBLIC_KEY_PATH=/app/community_solutions_jwt_public.pem

      - FRONTEND_TITLE_PREFIX=
      - FRONTEND_TITLE_SUFFIX=- Debug
      - FRONTEND_FAVICON_URL=https://betterinformatics.com/static/img/favicon.ico
      - FRONTEND_EMAIL_ADDRESS=nothing@localhost

      - PDEP_IS_PREVIEW=TRUE
    depends_on:
      - postgres
      - minio

# required so that the frontend docker can access the backend
networks:
  default:
    name: community-solutions
