version: "3"
services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    ports:
      - "9000:9000"
    volumes:
      - ./data/minio:/export
    command: server /export
  pgadmin:
    image: dpage/pgadmin4:4.26
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: docker
      PGADMIN_DEFAULT_PASSWORD: docker
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8082:80"
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
    depends_on:
      - "postgres"
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
    ports:
      - "5432:5432"
    volumes:
      - ./data/sql:/var/lib/postgresql/data
  community-solutions:
    build: .
    container_name: community-solutions
    ports:
      - "8081:80"
    environment:
      - DEPLOYMENT_DOMAIN=localhost

      - SIP_POSTGRES_DB_SERVER=postgres
      - SIP_POSTGRES_DB_PORT=5432
      - SIP_POSTGRES_DB_NAME=postgres
      - SIP_POSTGRES_DB_USER=docker
      - SIP_POSTGRES_DB_PW=docker

      - SIP_S3_FILES_HOST=minio
      - SIP_S3_FILES_PORT=9000
      - SIP_S3_FILES_ACCESS_KEY=minio
      - SIP_S3_FILES_SECRET_KEY=minio123
      - SIP_S3_FILES_BUCKET=community-solutions

      - RUNTIME_COMMUNITY_SOLUTIONS_SESSION_SECRET=42
      - RUNTIME_COMMUNITY_SOLUTIONS_API_KEY=42

      - RUNTIME_FRONTEND_KEYCLOAK_URL=https://auth.vseth.ethz.ch/auth
      - RUNTIME_FRONTEND_KEYCLOAK_REALM=VSETH

      - SIP_AUTH_OIDC_CLIENT_ID=vis-community-solutions
    depends_on:
      - "postgres"
      - "minio"
