version: "3.4"

services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/export
    command: server /export --console-address ":9001"
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " /usr/bin/mc config host add myminio http://minio:9000 minio minio123; /usr/bin/mc mb myminio/community-solutions; "
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
    volumes:
      - ./data/sql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  community-solutions:
    build:
      context: .
      args:
        git_branch: <docker>
        git_commit: <compose>
      target: backend
    container_name: community-solutions
    ports:
      - "8081:80"
    environment:
      - SIP_INGRESS_HTTP_DEFAULT_DEPLOYMENT_DOMAIN=localhost
      - SIP_INGRESS_HTTP_DEFAULT_CNAMES=

      - SIP_POSTGRES_DB_SERVER=postgres
      - SIP_POSTGRES_DB_PORT=5432
      - SIP_POSTGRES_DB_NAME=postgres
      - SIP_POSTGRES_DB_USER=docker
      - SIP_POSTGRES_DB_PW=docker

      - SIP_S3_FILES_HOST=minio
      - SIP_S3_FILES_PORT=9000
      - SIP_S3_FILES_ACCESS_KEY=minio
      - SIP_S3_FILES_SECRET_KEY=minio123
      - SIP_S3_FILES_BUCKET=community-solutions
      - SIP_S3_FILES_USE_SSL=false

      - RUNTIME_COMMUNITY_SOLUTIONS_SESSION_SECRET=42
      - RUNTIME_COMMUNITY_SOLUTIONS_API_KEY=42

      - RUNTIME_FRONTEND_KEYCLOAK_URL=https://auth.vseth.ethz.ch/auth
      - RUNTIME_FRONTEND_KEYCLOAK_REALM=VSETH

      - SIP_AUTH_OIDC_CLIENT_ID=vis_cat_staging_community_solutions_oidc
      - SIP_AUTH_OIDC_CLIENT_SECRET=tYousukJDxqlhpFuyonjmXyJm

      - FRONTEND_TITLE_PREFIX=prefix
      - FRONTEND_TITLE_SUFFIX=suffix
      - FRONTEND_FAVICON_URL=favicon
      - FRONTEND_EMAIL_ADDRESS=nothing@localhost

      - SIP_AUTH_OIDC_AUTH_ENDPOINT=https://auth.vseth.ethz.ch/auth/realms/VSETH/protocol/openid-connect/auth
      - SIP_AUTH_OIDC_TOKEN_ENDPOINT=https://auth.vseth.ethz.ch/auth/realms/VSETH/protocol/openid-connect/token

      - PDEP_IS_PREVIEW=TRUE
    depends_on:
      - postgres
      - minio

# required so that the frontend docker can access the backend
networks:
  default:
    name: community-solutions
