services:
  community-solutions:
    extends:
      file: docker-compose.yml
      service: community-solutions
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4317
      - OTEL_SERVICE_VERSION=local-dev
      - OTEL_LOG_LEVEL=debug
      - DJANGO_SETTINGS_MODULE=backend.settings

  react-frontend:
    extends:
      file: docker-compose.yml
      service: react-frontend
    environment:
      - VITE_FARO_DISABLE=false

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./contrib/local-observability/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-remote-write-receiver"
      - "--enable-feature=native-histograms"
    ports:
      - 9090:9090
    user: ":"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./contrib/local-observability/grafana:/etc/grafana/provisioning
    user: ":"

  alloy:
    image: grafana/alloy:latest
    ports:
      - "12345:12345"
      - "12347:12347"
    volumes:
      - ./contrib/local-observability/config.alloy:/etc/alloy/config.alloy
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
      - "9600:9600"
    command: -config.file=/etc/loki/local-config.yml --log.level=info
    volumes:
      - ./contrib/local-observability/loki-local-config.yml:/etc/loki/local-config.yml

  tempo:
    image: grafana/tempo:latest
    ports:
      - "3200:3200"
    command: -config.file=/etc/tempo/tempo.yml
    volumes:
      - ./contrib/local-observability/tempo.yml:/etc/tempo/tempo.yml
