# Generated by Django 3.2.18 on 2023-10-22 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myauth", "0003_auto_20210326_1549"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="old_profile",
                to="myauth.myuser",
            ),
        ),
    ]
