# Generated by Django 3.0.2 on 2020-01-14 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayname', models.CharField(max_length=256)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.MetaCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayname', models.CharField(max_length=256)),
                ('slug', models.CharField(max_length=256)),
                ('admins', models.ManyToManyField(related_name='category_admin_set', to=settings.AUTH_USER_MODEL)),
                ('experts', models.ManyToManyField(related_name='category_expert_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
