# Generated by Django 3.0.2 on 2020-01-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_categories',
            field=models.ManyToManyField(related_name='category_set', to='categories.MetaCategory'),
        ),
        migrations.AddField(
            model_name='metacategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
