# Generated by Django 3.0.2 on 2020-01-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20200115_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='form',
            field=models.CharField(choices=[('written', 'written'), ('oral', 'oral')], default='written', max_length=256),
        ),
        migrations.AddField(
            model_name='category',
            name='has_payments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='more_exams_link',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='category',
            name='permission',
            field=models.CharField(choices=[('public', 'public'), ('intern', 'intern'), ('hidden', 'hidden'), ('none', 'none')], default='public', max_length=64),
        ),
        migrations.AddField(
            model_name='category',
            name='remark',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='semester',
            field=models.CharField(choices=[('FS', 'FS'), ('HS', 'HS')], default='FS', max_length=2),
            preserve_default=False,
        ),
    ]
