# Generated by Django 3.0.2 on 2020-01-15 14:11

from django.db import migrations


def add_default_category(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Type = apps.get_model('categories', 'Category')
    Type.objects.using(db_alias).create(displayname='default', slug='default')


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20200115_1332'),
    ]

    operations = [
        migrations.RunPython(add_default_category)
    ]
