# Generated by Django 3.0.2 on 2020-01-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20200115_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='semester',
            field=models.CharField(choices=[('--', '--'), ('FS', 'FS'), ('HS', 'HS')], default='--', max_length=2),
        ),
    ]
