# Generated by Django 3.0.2 on 2020-04-11 09:36

from django.db import migrations


def rename_categories(apps, schema_editor):
    Category = apps.get_model("categories", "Category")
    Category.objects.filter(slug="").update(slug="<empty name>")


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0008_count_ignore_hidden"),
    ]

    operations = [
        migrations.RunPython(rename_categories)
    ]
