# Generated by Django 4.1.13 on 2023-12-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_category_count_ignore_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='permission',
            field=models.CharField(choices=[('public', 'public'), ('internal', 'internal'), ('hidden', 'hidden'), ('none', 'none')], default='public', max_length=64),
        ),
        migrations.AlterField(
            model_name='category',
            name='semester',
            field=models.CharField(choices=[('--', '--'), ('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2'), ('Full Year', 'Full Year')], default='--', max_length=10),
        ),
    ]
