# Generated by Django 4.1.13 on 2023-12-26 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0011_alter_category_permission_alter_category_semester"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="has_payments",
        ),
    ]
