# Generated by Django 5.2.15 on 2026-07-10 19:29

import django.db.models.deletion
import django_prometheus.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0012_add_document_count_to_meta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryUserPinned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('category', 'user'), name='unique_user_category_pin')],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('category_user_pinned'), models.Model),
        ),
    ]
