# Generated by Django 4.1.13 on 2023-12-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0013_add_document_counts_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="more_markdown_link",
            field=models.CharField(default="", max_length=512),
        ),
    ]
