# Generated by Django 4.1.13 on 2024-01-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0014_add_category_more_markdown_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="semester",
            field=models.CharField(
                choices=[
                    ("none", "none"),
                    ("sem1", "sem1"),
                    ("sem2", "sem2"),
                    ("full", "full"),
                ],
                default="none",
                max_length=10,
            ),
        ),
    ]
