# Generated by Django 4.1.13 on 2024-01-15 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0015_alter_category_semester"),
    ]

    operations = [
        migrations.CreateModel(
            name="EuclidCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=12)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="euclid_codes",
                        to="categories.category",
                    ),
                ),
            ],
        ),
    ]
