# Generated by Django 4.1.13 on 2025-09-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0018_coursestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestats',
            name='course_organiser',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
