# Generated by Django 5.2.16 on 2026-08-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0021_add_percentile_stats_and_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestats',
            name='student_count',
            field=models.IntegerField(null=True),
        ),
    ]
