# Generated by Django 5.2.16 on 2026-08-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0023_alter_coursestats_options_coursestats_source_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestats',
            name='course_organiser',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
