# Generated by Django 4.1.13 on 2026-06-06 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0019_coursestats_course_organiser"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("testimonial", models.TextField()),
                ("year_taken", models.IntegerField()),
                (
                    "approval_status",
                    models.IntegerField(
                        choices=[(0, "Approved"), (1, "Pending"), (2, "Rejected")],
                        default=1,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.category",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="testimonial",
            constraint=models.UniqueConstraint(
                condition=models.Q(("approval_status__in", [0, 1])),
                fields=("author", "category"),
                name="unique_approved_or_pending_per_author_course",
            ),
        ),
    ]
