# Generated by Django 4.1.13 on 2026-08-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testimonials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="slug",
            field=models.CharField(default="", max_length=256, unique=True),
        ),
    ]
