# Generated by Django 5.2.16 on 2026-08-17 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testimonials", "0002_testimonial_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testimonial",
            name="slug",
        ),
    ]
