# Generated by Django 4.1.13 on 2026-07-19 01:50

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ediauth", "0006_profile_remove_primary_key_from_display_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("session_id", models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
