# Generated by Django 3.0.2 on 2020-01-14 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('payment_time', models.DateTimeField()),
                ('check_time', models.DateTimeField()),
                ('refund_time', models.DateTimeField()),
                ('uploaded_transcript', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='answers.Exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
