# Generated by Django 3.0.2 on 2020-01-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20200114_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
