# Generated by Django 3.0.2 on 2020-01-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20200114_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='check_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='refund_time',
            field=models.DateTimeField(null=True),
        ),
    ]
