# Generated by Django 3.0.2 on 2020-01-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20200119_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='active',
        ),
    ]
