# Generated by Django 3.0.2 on 2020-04-11 09:36

from django.db import migrations


def rename_categories(apps, schema_editor):
    Category = apps.get_model("documents", "Document")
    Category.objects.filter(display_name="").update(display_name="<empty label>")


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0007_auto_20210513_1321"),
    ]

    operations = [
        migrations.RunPython(rename_categories)
    ]
