# Generated by Django 3.2.18 on 2023-05-30 18:16

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_remove_empty_documents'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='documents_c_search__02d77d_gin',
        ),
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='documents_c_search__fb153e_gin'),
        ),
    ]
