# Generated by Django 4.1.13 on 2024-01-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0013_alter_comment_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="anonymised",
            field=models.BooleanField(default=False),
        ),
    ]
