# Generated by Django 4.1.13 on 2025-10-22 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0015_20240413_merge_upstream'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='flagged',
            field=models.ManyToManyField(related_name='flagged_%(app_label)s_comments_set', to=settings.AUTH_USER_MODEL),
        ),
    ]