# Generated by Django 4.1.13 on 2025-10-31 20:25

from django.db import migrations, models

def set_order(apps, schema_editor):
    Document = apps.get_model('documents', 'Document')
    DocumentFile = apps.get_model('documents', 'DocumentFile')

    for document in Document.objects.all():
        document_files = DocumentFile.objects.filter(document=document).all()
        for index, document_file in enumerate(document_files):
            document_file.order = index

        DocumentFile.objects.bulk_update(document_files, ['order'])

class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_20251022_merge_upstream'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(set_order),
    ]