# Generated by Django 4.1.13 on 2026-03-17 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0017_20251126_merge_upstream"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="marked_as_ai",
            field=models.ManyToManyField(
                related_name="markedasai_%(app_label)s_comments_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
