import * as React from "react";
import useTitle from "../hooks/useTitle";
import serverData from "../utils/server-data";
import { Title, Container } from "@mantine/core";

export const PrivacyPolicyPage: React.FC = () => {
  useTitle("Privacy Policy");

  return (
    <Container size="xl">
      <Title order={1} mb="md">
        Privacy Policy
      </Title>
      <Title order={2}>Our Contact Details</Title>
      <p>
        <b>Name: </b> CompSoc Better Informatics <br />
        <b>Address: </b> CompSoc, School of Informatics, Informatics Forum, 10
        Crichton Street, Edinburgh, EH8 9AB. <br />
        <b>Email: </b>{" "}
        <a href={`mailto:${serverData.email_address}`}>
          {serverData.email_address}
        </a>
      </p>

      <Title order={2}>Types of personal information collected</Title>
      <p>
        We currently collect and process the following information:
        <ul>
          <li>Student UUN (i.e. username)</li>
          <li>IP Address (stored ephemeraly during login)</li>
          <li>Account creation date</li>
          <li>Last login date</li>
          <li>
            Anonymised browsing behaviour on the platform such as visited pages
            and time spent on each page
          </li>
          <li>Your activity, such as upvotes, downvotes, reports</li>
          <li>
            Your dissertation details and full contents, if you choose to submit
            them
          </li>
          <li>
            Any other information you intentionally share on the platform
            through public content submissions
          </li>
        </ul>
      </p>

      <Title order={2}>
        How we get the personal information and why we have it
      </Title>
      <p>
        <b>Your Student UUN and IP address</b> are provided to us directly by
        you or your browser for authentication and identification purposes. We
        use the information that you have given us in order to limit access to
        Better Informatics and its community-provided documents to current
        University of Edinburgh students.
      </p>
      <p>
        Under the UK General Data Protection Regulation (UK GDPR), the lawful
        bases we rely on for processing this information are:
        <ul>
          <li>
            Contractual necessity. In order to provide the features we promise
            to our users including you, we need to verify using your UUN that
            you are a current University of Edinburgh student. Furthermore, we
            use your IP address to detect and prevent malicious login attempts
            in order to maintain the availability of our service.
          </li>
        </ul>
      </p>
      <p>
        <b>Your account creation date</b> is automatically generated by our
        system when you create an account, and <b>your last login date</b> is
        automatically updated by our system whenever you log in. We use the
        information that you have given us to track user growth. As gradually
        students lose access to their university accounts after graduation, we
        also use the last login date to estimate accounts of graduated users
        that we can exclude from our active user metrics.
      </p>
      <p>
        Under the UK GDPR, the lawful bases we rely on for processing this
        information are:
        <ul>
          <li>
            Legitimate interests. We have a legitimate interest in tracking the
            growth of our user base in order to decide how much resources to
            invest in maintaining and improving our service. You have the right
            to object to the processing of this information, and you can do so
            at any time. As some of this information is structural to our
            database, we may not be able to delete it upon request, but we can
            exclude it from our user metrics. Please contact us at{" "}
            <a href={`mailto:${serverData.email_address}`}>
              {serverData.email_address}
            </a>
            .
          </li>
        </ul>
      </p>
      <p>
        <b>Your anonymised browsing behaviour on the platform</b> is tracked by
        our system automatically via JavaScript. We use this information to
        understand browsing behaviour on our platform to target development
        priorities.
      </p>
      <p>
        Under the UK GDPR, the lawful bases we rely on for processing this
        information are:
        <ul>
          <li>
            Legitimate interests. We have a legitimate interest in understanding
            how users browse our platform in order to prioritise which site
            pages to focus UX improvements on. You have the right to object to
            the processing of this information, and you can do so at any time.
            Please contact us at{" "}
            <a href={`mailto:${serverData.email_address}`}>
              {serverData.email_address}
            </a>
            .
          </li>
        </ul>
      </p>
      <p>
        <b>
          Your activity on the platform, such as upvotes, downvotes, and reports
        </b>
        , are tracked and stored by our system when you interact with the
        relevant features. We use this information for curating the content
        displayed on our platform, which benefits the community.
      </p>
      <p>
        Under the UK GDPR, the lawful bases we rely on for processing this
        information are:
        <ul>
          <li>
            Legitimate interests. We have a legitimate interest in curating the
            content on our platform in order to operate, maintain, and preserve
            a primarily community-driven knowledge archive for the benefit of
            current and future students. You have the right to object to the
            processing of this information, and you can do so at any time. You
            can do this by ceasing to use the relevant features, which are not
            required for the core offering of Better Informatics. For a manual
            alternative, you can contact us at{" "}
            <a href={`mailto:${serverData.email_address}`}>
              {serverData.email_address}
            </a>
            .
          </li>
        </ul>
      </p>
      <p>
        <b>Your dissertation details and full contents</b>, if you choose to
        submit them, are provided to us directly by you for the purpose of
        creating a searchable database of volunteer-contributed past
        dissertations. You may choose to redact some words from your
        dissertation when you upload it. You may choose to not upload your
        dissertation at all. The entire offering of Better Informatics is
        available to you regardless of whether you upload one or not.
      </p>
      <p>
        Under the UK GDPR, the lawful bases we rely on for processing this
        information are:
        <ul>
          <li>
            Legitimate interests. Should you choose to submit your dissertation,
            we have a legitimate interest in processing that information for the
            purpose of achieving our mission as a provider of a community-driven
            knowledge archive. You have the right to object to the processing of
            this information, and you can do so at any time. You can do this by
            deleting the dissertation that you have uploaded, which instantly
            removes the information and files from our servers. For a manual
            alternative, you can contact us at{" "}
            <a href={`mailto:${serverData.email_address}`}>
              {serverData.email_address}
            </a>
            .
          </li>
        </ul>
      </p>
      <p>
        <b>
          Any other information you share on the platform through free-form
          submissions such as resources, answers, comments, and course reviews
        </b>
        , are provided to us directly by you by your own judgement and help us
        build a community-driven platform. We discourage the sharing of overly
        personal information through these channels, as some of them will be
        made public to the internet without authentication. The entire offering
        of Better Informatics is available to you regardless of your inclusion
        of personal information.
      </p>
      <p>
        Under the UK GDPR, the lawful bases we rely on for processing this
        information are:
        <ul>
          <li>
            Legitimate interests. Should you choose to make a submission
            containing personal information, we have a legitimate interest in
            processing it and sharing it with other users for the purpose of
            achieving our mission as a provider of a community-driven knowledge.
            Specifically with regards to resources and reviews, this may also
            extend to sharing the content with the wider internet without
            authentication. You have the right to object to the processing of
            this information, and you can do so at any time. You can do this by
            deleting the relevant submission. For a manual alternative, you can
            contact us at{" "}
            <a href={`mailto:${serverData.email_address}`}>
              {serverData.email_address}
            </a>
            .
          </li>
        </ul>
      </p>

      <Title order={2}>How we store your personal information</Title>
      <p>
        Your IP address is only stored ephemerally during the login request in
        order to perform security checks. After the login request is completed,
        the IP address is deleted from our servers.
      </p>
      <p>
        Your student UUN and all other contributed data are securely stored on
        our servers hosted physically in Edinburgh by the Tardis Project.
        Because these data form a permanent educational resource that is
        integral to the platform, we will keep these indefinitely. If you choose
        to delete your account, your personal identifiers (such as your student
        UUN) will be scrubbed, but your contributed content will be retained in
        an anonymised format unless you specifically request their deletion too.
      </p>
      <p>
        Additionally, an encrypted backup of all data including your personal
        information is stored on cloud storage services. This is to ensure that
        we can recover production data in the event of Tardis (our host)
        experiencing data loss. The encryption key is known to and managed by
        only the Better Informatics server administrator(s).
      </p>

      <Title order={2}>Your data protection rights</Title>
      <p>
        Under data protection law, you have rights including:
        <ul>
          <li>
            <b>Your Right to Access & Data Portability</b> - You have the right
            to receive your personal information in a structured, commonly used
            format.
          </li>
          <li>
            <b>Your Right to Erasure</b> - You have the right to ask us to erase
            your personal information.
          </li>
          <li>
            <b>Your Right to Restrict or Object to Processing</b> - You have the
            right to object to the processing of your personal information
            and/or request restrictions on such processing.
          </li>
          <li>
            <b>Your Right to Lodge a Complaint</b> - You have the right to lodge
            a complaint with the UK Information Commissioner's Office (ICO) if
            you believe that your data protection rights have been infringed.
          </li>
          <li>
            <b>Your Right to Rectification</b> - You have the right to ask us to
            rectify inaccurate personal information we hold about you. All
            functionality of Better Informatics with an upload or contribution
            feature has an associated delete or edit feature.
          </li>
        </ul>
        You are not required to pay any charge for exercising your rights. If
        you make a request, we have one month to respond to you. Please contact
        us at{" "}
        <a href={`mailto:${serverData.email_address}`}>
          {serverData.email_address}
        </a>
        .
      </p>

      <Title order={2}>How to complain</Title>
      <p>
        If you have any concerns about our use of your personal information, you
        can make a complaint to us at{" "}
        <a href={`mailto:${serverData.email_address}`}>
          {serverData.email_address}
        </a>
        .
      </p>

      <Title order={2}>History of Changes to this Policy</Title>
      <p>
        <ul>
          <li>2024-01-13: Initial revision</li>
          <li>
            2026-06-01:{" "}
            <a
              href="/static/privacy-policy-diff-2026-06-01.pdf"
              target="_blank"
              rel="noopener noreferrer"
            >
              Updated privacy policy
            </a>
          </li>
        </ul>
      </p>
    </Container>
  );
};
export default PrivacyPolicyPage;
