{
 "title": "Community Solutions",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(django_http_requests_total_by_view_transport_method_total,namespace)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(django_http_requests_total_by_view_transport_method_total{namespace=~\"$namespace\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "External requests (ingress)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{ingress=\"community-solutions-http\", exported_namespace=\"$namespace\"}[2m])) by (ingress), 0.001)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Average request distribution over time",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(django_http_requests_total_by_view_transport_method_total{namespace=~\"$namespace\", job=~\"^$job$\",view!~\"django_prometheus.exports.ExportToDjangoView|health\"}[2m])) by (view), 0.001)",
     "legendFormat": "{{view}}"
    }
   ]
  },
  {
   "title": "Model insertions",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(increase(django_model_inserts_total{namespace=~\"$namespace\", job=~\"^$job$\", model=~\"answer|comment|document\"}[$__range])) by (model)",
     "legendFormat": "New {{model}}s",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Requests/sec per Django view",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(sum(irate(django_http_requests_total_by_view_transport_method_total{namespace=~\"$namespace\", job=~\"^$job$\",view!~\"django_prometheus.exports.ExportToDjangoView|health\"}[2m])) by (view), 0.001)",
     "legendFormat": "{{view}}"
    }
   ]
  },
  {
   "title": "Kubernetes: #replicas",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "avg(kube_deployment_status_replicas{exported_namespace=~\"$namespace\", deployment=~\"community-solutions\"})",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Pods running",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"community-solutions-.*\"}) by (pod_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request success rate (2xx / all)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{status=~\"2.+|403|401\",namespace=~\"$namespace\", job=~\"^$job$\"}[$__interval])) / sum(irate(django_http_responses_total_by_status_total{namespace=~\"$namespace\", job=~\"^$job$\"}[$__interval]))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(django_model_updates_total{namespace=~\"$namespace\", job=~\"^$job$\", model=~\"comment|document\"}[$__range])) by (model)",
     "legendFormat": "Updated {{ model }}s"
    },
    {
     "expr": "sum(increase(django_model_deletes_total{namespace=~\"$namespace\", job=~\"^$job$\", model=~\"answer|comment|document\"}[$__range])) by (model)",
     "legendFormat": "Deleted {{ model }}s"
    }
   ]
  },
  {
   "title": "Upvotes/Downvotes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(django_http_requests_total_by_view_transport_method_total{namespace=~\"$namespace\", job=~\"^$job$\",view=\"setlike\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Requests/sec by method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(sum(irate(django_http_requests_total_by_method_total{namespace=~\"$namespace\", job=~\"^$job$\",view!~\"django_prometheus.exports.ExportToDjangoView|health\"}[2m])) by (method), 0.001)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Ops",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(django_db_execute_total{namespace=~\"$namespace\", job=~\"^$job$\"}[$__interval])) by (vendor)",
     "legendFormat": "{{vendor}}"
    }
   ]
  },
  {
   "title": "Response Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{namespace=~\"$namespace\", job=~\"^$job$\", view!~\"prometheus-django-metrics|healthcheck\"}[$__interval])) by(status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{namespace=~\"$namespace\", job=~\"^$job$\",view!~\"prometheus-django-metrics|healthcheck\"}[$__rate_interval])) by (job, le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{namespace=~\"$namespace\", job=~\"^$job$\",view!~\"prometheus-django-metrics|healthcheck\"}[$__rate_interval])) by (job, le))",
     "legendFormat": "95th quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{namespace=~\"$namespace\", job=~\"^$job$\",view!~\"prometheus-django-metrics|healthcheck\"}[$__rate_interval])) by (job, le))",
     "legendFormat": "99th quantile"
    }
   ]
  },
  {
   "title": "Responses per replica",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_before_middlewares_total{namespace=~\"$namespace\", job=~\"^$job$\", view!~\"prometheus-django-metrics|healthcheck\"}[$__interval])) by(instance)",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Container memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"community-solutions-.*\"}) by (namespace, pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"community-solutions-.*\"}[5m])) by (namespace, pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "DB Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(django_db_query_duration_seconds_bucket{namespace=\"$namespace\", job=\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "99.9th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_db_query_duration_seconds_bucket{namespace=\"$namespace\", job=\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(django_db_query_duration_seconds_bucket{namespace=\"$namespace\", job=\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(django_db_query_duration_seconds_bucket{namespace=\"$namespace\", job=\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "50th percentile"
    }
   ]
  }
 ]
}