# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import people_pb2 as people__pb2


class PeopleStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetVisLegacyPerson = channel.unary_unary(
        '/people.People/GetVisLegacyPerson',
        request_serializer=people__pb2.GetPersonRequest.SerializeToString,
        response_deserializer=people__pb2.VisLegacyPerson.FromString,
        )
    self.AuthVisLegacyPerson = channel.unary_unary(
        '/people.People/AuthVisLegacyPerson',
        request_serializer=people__pb2.AuthPersonRequest.SerializeToString,
        response_deserializer=people__pb2.AuthPersonResponse.FromString,
        )
    self.ListVisLegacyPeopleStream = channel.unary_stream(
        '/people.People/ListVisLegacyPeopleStream',
        request_serializer=people__pb2.ListPeopleRequest.SerializeToString,
        response_deserializer=people__pb2.VisLegacyPerson.FromString,
        )
    self.ListVisLegacyPeople = channel.unary_unary(
        '/people.People/ListVisLegacyPeople',
        request_serializer=people__pb2.ListPeopleRequest.SerializeToString,
        response_deserializer=people__pb2.ListVisLegacyPeopleResponse.FromString,
        )
    self.GetEthPerson = channel.unary_unary(
        '/people.People/GetEthPerson',
        request_serializer=people__pb2.GetPersonRequest.SerializeToString,
        response_deserializer=people__pb2.EthPerson.FromString,
        )
    self.AuthEthPerson = channel.unary_unary(
        '/people.People/AuthEthPerson',
        request_serializer=people__pb2.AuthPersonRequest.SerializeToString,
        response_deserializer=people__pb2.AuthPersonResponse.FromString,
        )
    self.CheckLiveness = channel.unary_unary(
        '/people.People/CheckLiveness',
        request_serializer=people__pb2.Empty.SerializeToString,
        response_deserializer=people__pb2.Empty.FromString,
        )
    self.CheckReadiness = channel.unary_unary(
        '/people.People/CheckReadiness',
        request_serializer=people__pb2.Empty.SerializeToString,
        response_deserializer=people__pb2.Empty.FromString,
        )


class PeopleServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetVisLegacyPerson(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthVisLegacyPerson(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListVisLegacyPeopleStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListVisLegacyPeople(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetEthPerson(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthEthPerson(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CheckLiveness(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CheckReadiness(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PeopleServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetVisLegacyPerson': grpc.unary_unary_rpc_method_handler(
          servicer.GetVisLegacyPerson,
          request_deserializer=people__pb2.GetPersonRequest.FromString,
          response_serializer=people__pb2.VisLegacyPerson.SerializeToString,
      ),
      'AuthVisLegacyPerson': grpc.unary_unary_rpc_method_handler(
          servicer.AuthVisLegacyPerson,
          request_deserializer=people__pb2.AuthPersonRequest.FromString,
          response_serializer=people__pb2.AuthPersonResponse.SerializeToString,
      ),
      'ListVisLegacyPeopleStream': grpc.unary_stream_rpc_method_handler(
          servicer.ListVisLegacyPeopleStream,
          request_deserializer=people__pb2.ListPeopleRequest.FromString,
          response_serializer=people__pb2.VisLegacyPerson.SerializeToString,
      ),
      'ListVisLegacyPeople': grpc.unary_unary_rpc_method_handler(
          servicer.ListVisLegacyPeople,
          request_deserializer=people__pb2.ListPeopleRequest.FromString,
          response_serializer=people__pb2.ListVisLegacyPeopleResponse.SerializeToString,
      ),
      'GetEthPerson': grpc.unary_unary_rpc_method_handler(
          servicer.GetEthPerson,
          request_deserializer=people__pb2.GetPersonRequest.FromString,
          response_serializer=people__pb2.EthPerson.SerializeToString,
      ),
      'AuthEthPerson': grpc.unary_unary_rpc_method_handler(
          servicer.AuthEthPerson,
          request_deserializer=people__pb2.AuthPersonRequest.FromString,
          response_serializer=people__pb2.AuthPersonResponse.SerializeToString,
      ),
      'CheckLiveness': grpc.unary_unary_rpc_method_handler(
          servicer.CheckLiveness,
          request_deserializer=people__pb2.Empty.FromString,
          response_serializer=people__pb2.Empty.SerializeToString,
      ),
      'CheckReadiness': grpc.unary_unary_rpc_method_handler(
          servicer.CheckReadiness,
          request_deserializer=people__pb2.Empty.FromString,
          response_serializer=people__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'people.People', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
