# Generated by Django 4.1.13 on 2026-04-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="reply",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="feedback",
            name="reply_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
