# Generated by Django 3.0.2 on 2020-01-14 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
