# Generated by Django 3.0.2 on 2020-01-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20200114_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
