# Generated by Django 3.0.2 on 2020-01-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestore', '0002_attachment_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='filename',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
